import { AnimatePresence, motion } from 'motion/react'
import { useEffect } from 'react'
import { DownloadIcon } from '../layout/TopBar'

type ExportDrawerProps = { open: boolean; csvPreview: string; error?: string; onClose: () => void; onDownloadCsv: () => void; onDownloadIcs: () => void }

/** Render the export drawer with the current schedule preview. */
export function ExportDrawer({ open, csvPreview, error, onClose, onDownloadCsv, onDownloadIcs }: ExportDrawerProps) {
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === 'Escape' && open) onClose() }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler) }, [open, onClose])
  return <AnimatePresence>{open && <><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.2, ease: 'easeOut' }} className="fixed inset-0 z-300 bg-ink/30" onClick={onClose} /><motion.div role="dialog" aria-modal="true" aria-label="Export pour schedule" initial={{ x: 40, opacity: 0, filter: 'blur(8px)' }} animate={{ x: 0, opacity: 1, filter: 'blur(0px)' }} exit={{ x: 24, opacity: 0, filter: 'blur(4px)' }} transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }} className="fixed right-0 top-0 z-400 flex h-full w-full max-w-[360px] flex-col border-l border-line-2 bg-elevated p-6"><div className="flex items-center justify-between"><p className="font-mono text-[0.6875rem] font-medium uppercase tracking-[0.12em] text-text-3">export schedule</p><button onClick={onClose} aria-label="Close export drawer" className="rounded-full px-3 py-2 text-sm text-text-2 transition-colors hover:text-ink focus-visible:ring-2 focus-visible:ring-accent">close</button></div><div className="mt-6 space-y-4"><ExportRow name="curo-pour-plan.csv" onDownload={onDownloadCsv} /><ExportRow name="curo-pour-plan.ics" onDownload={onDownloadIcs} /></div>{error && <p className="mt-4 rounded-lg border border-error/30 bg-error/8 p-3 font-mono text-[0.6875rem] text-error">{error}</p>}<div className="mt-8 rounded-lg border border-line-2 bg-bg-2 p-3"><p className="mb-2 font-mono text-[10px] uppercase tracking-[0.12em] text-text-3">csv preview</p><pre className="max-h-[340px] overflow-auto whitespace-pre-wrap font-mono text-[0.6875rem] leading-relaxed text-text-2 hide-scrollbar">{csvPreview || 'preview appears when live schedule data is available'}</pre></div><p className="mt-auto font-mono text-[10px] uppercase tracking-[0.12em] text-text-3">imports into procore · ms project · any scheduler</p></motion.div></>}</AnimatePresence>
}

function ExportRow({ name, onDownload }: { name: string; onDownload: () => void }) { return <div className="flex items-center gap-3 rounded-lg border border-line-2 bg-bg-2 p-3"><p className="min-w-0 flex-1 truncate font-mono text-[0.6875rem] text-text-2">{name}</p><button onClick={onDownload} aria-label={`Download ${name}`} className="flex min-h-11 min-w-11 items-center justify-center rounded-full border border-line-2 text-ink transition-colors hover:border-ink/40 focus-visible:ring-2 focus-visible:ring-accent"><DownloadIcon /></button></div> }

