import { motion } from 'motion/react'
import { useEffect, useState } from 'react'
import type { DayWindow, ForecastHour, ModelWindow, Site, Status } from '../../lib/types'
import { DownloadIcon } from '../layout/TopBar'
import { FadeBlur } from '../ui/FadeBlur'

type DecisionRailProps = { site: Site; forecast: ForecastHour[]; days: DayWindow[]; model: ModelWindow | null; errors: string[]; onExportCsv: () => void; onExportIcs: () => void; onRetry: () => void; onAlert: () => void }

function statusLabel(status: Status | undefined): string { return status === 'green' ? 'safe to pour' : status === 'amber' ? 'window closing' : status === 'red' ? 'do not pour' : 'waiting for temperature' }

function RuleLine({ ok, warn, label }: { ok?: boolean; warn?: boolean; label: string }) {
  return <p className="flex items-center gap-2 font-mono text-[0.6875rem] text-text-2">{ok ? <svg className="h-3.5 w-3.5 text-success" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4 10-10" /></svg> : warn ? <svg className="h-3.5 w-3.5 text-warning" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v4m0 4h.01" /></svg> : null}{label}</p>
}

function useCount(target: number, delay = 600): number {
  const [value, setValue] = useState(0)
  useEffect(() => { const startTimer = window.setTimeout(() => { const start = performance.now(); const tick = (now: number) => { const progress = Math.min((now - start) / 1200, 1); setValue(Math.round(target * (1 - Math.pow(1 - progress, 3)))); if (progress < 1) window.requestAnimationFrame(tick) }; window.requestAnimationFrame(tick) }, delay); return () => window.clearTimeout(startTimer) }, [target, delay])
  return value
}

/** Render the single-surface decision rail and its live model outputs. */
export function DecisionRail({ site, forecast, days, model, errors, onExportCsv, onExportIcs, onRetry, onAlert }: DecisionRailProps) {
  const worst = model?.worst
  const avoided = model?.hours.filter((hour) => hour.status === 'red').length || 0
  const cost = useCount(avoided * site.pour_cost)
  const co2 = useCount(Math.round(avoided * site.re_pour_co2 * 10)) / 10
  const firstHour = model?.hours[0]
  return <aside className="col-span-12 flex min-h-0 flex-col overflow-y-auto rounded-xl border border-line-2 bg-surface hide-scrollbar lg:col-span-5">
    {errors.length > 0 && <div className="m-4 flex items-center gap-3 rounded-lg border border-error/30 bg-error/8 p-3"><svg className="h-4 w-4 shrink-0 text-error" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v4m0 4h.01" /></svg><p className="font-mono text-[0.6875rem] text-ink">api unavailable · configure key, then retry</p><button onClick={onRetry} className="ml-auto rounded-full border border-line-2 px-3 py-1.5 text-sm font-medium text-ink transition-colors hover:border-ink/40 focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-surface">retry</button></div>}
    <FadeBlur delay={0.2}><section className="border-b border-line p-4 lg:p-5"><p className="font-mono text-[0.6875rem] font-medium uppercase tracking-[0.12em] text-text-3">site 01 · pour window</p><div className={`mt-3 rounded-lg border-l-4 p-3 transition-colors duration-400 ${worst === 'green' ? 'border-success bg-success/8' : worst === 'amber' ? 'border-warning bg-warning/8' : worst === 'red' ? 'border-error bg-error/8' : 'border-line-2 bg-bg-2'}`}><p className="font-ui text-lg font-semibold text-ink">{statusLabel(worst)}</p><p className="mt-1 font-mono text-[0.6875rem] tabular-nums text-text-2">{firstHour && model ? `${firstHour.tempF.toFixed(1)}°f · margin ${firstHour.marginF?.toFixed(1)}°f · limit ${model.limitF.toFixed(0)}°f · source model` : 'waiting for live temperature data'}</p></div><div className="mt-3 space-y-1.5"><RuleLine ok={Boolean(model)} label={`placement limit ${model?.limitF.toFixed(0) || '95'}°f · aci 305r-20 · source model`} /><RuleLine ok={Boolean(model)} label="temperature source returned by FortyGuard" /><RuleLine warn label={`slab thickness ${site.thickness}in · amber band ±${model?.amberBandF || 5}°f · assumption`} /></div>{worst === 'red' && <button onClick={onAlert} className="mt-4 rounded-full border border-error/30 px-3 py-2 text-sm font-medium text-error transition-colors hover:border-error focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-surface">open breach alert</button>}</section></FadeBlur>
    <FadeBlur delay={0.3}><section className="border-b border-line p-4 lg:p-5"><div className="flex items-center justify-between"><p className="font-mono text-[0.6875rem] font-medium uppercase tracking-[0.12em] text-text-3">next 12 hours</p><p className="font-mono text-[0.6875rem] text-text-3">api forecast</p></div><div className="mt-3 grid min-w-[520px] grid-cols-12 gap-1 overflow-x-auto hide-scrollbar">{forecast.map((hour) => <div key={hour.timestamp} className={`flex h-16 flex-col items-center justify-center gap-1 rounded-md ${hour.status === 'green' ? 'bg-success/10' : hour.status === 'amber' ? 'bg-warning/10' : hour.status === 'red' ? 'bg-error/10' : 'bg-bg-2'}`}><span className={`font-mono text-[0.6875rem] tabular-nums ${hour.status === 'red' ? 'text-error' : 'text-ink'}`}>{hour.tempF.toFixed(0)}°</span><span className="font-mono text-[10px] text-text-3">{hour.hour}</span></div>)}</div>{forecast.length === 0 && <p className="mt-3 font-mono text-[0.6875rem] text-text-3">forecast appears when the api key is configured</p>}</section></FadeBlur>
    <FadeBlur delay={0.4}><section className="border-b border-line p-4 lg:p-5"><div className="flex items-center justify-between gap-3"><p className="font-mono text-[0.6875rem] font-medium uppercase tracking-[0.12em] text-text-3">two week window</p><div className="hidden items-center gap-2 sm:flex"><span className="font-mono text-[10px] uppercase tracking-[0.12em] text-text-3">first 12h forecast</span><span className="font-mono text-[10px] uppercase tracking-[0.12em] text-text-3">then climatology p25 to p75</span></div></div><div className="mt-3 grid grid-cols-7 gap-1.5">{days.map((day) => <div key={day.date} className="rounded-lg border border-line-2 bg-elevated p-2"><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-text-3">{day.weekday}</p><p className="mt-0.5 font-mono text-[0.6875rem] tabular-nums text-ink">{day.date.slice(8)}</p><div className={`mt-1.5 h-1.5 rounded-full ${day.worst === 'red' ? 'bg-error' : day.worst === 'amber' ? 'bg-warning' : 'bg-success'}`} /><p className="mt-1.5 font-mono text-[10px] tabular-nums text-text-2">{day.range}</p><p className="font-mono text-[10px] tabular-nums text-text-3">model · {day.confidence}</p><p className="font-mono text-[9px] uppercase tracking-[0.08em] text-text-3">api {day.source}</p></div>)}</div>{days.length === 0 && <p className="mt-3 font-mono text-[0.6875rem] text-text-3">history appears when live samples are available</p>}</section></FadeBlur>
    <FadeBlur delay={0.5}><section className="p-4 lg:p-5"><div className="grid grid-cols-2 gap-3"><div className="rounded-lg border border-line-2 bg-elevated p-3"><p className="font-mono text-[0.6875rem] font-medium uppercase tracking-[0.12em] text-text-3">cost avoided</p><p className="mt-2 font-ui text-[2rem] font-bold leading-none tracking-[-0.02em] tabular-nums text-ink">${cost.toLocaleString()}</p><p className="mt-1.5 font-mono text-[10px] text-text-3">assumption · ${site.pour_cost.toLocaleString()} per failed pour · {avoided} avoided</p></div><div className="rounded-lg border border-line-2 bg-elevated p-3"><p className="font-mono text-[0.6875rem] font-medium uppercase tracking-[0.12em] text-text-3">co2 avoided</p><p className="mt-2 font-ui text-[2rem] font-bold leading-none tracking-[-0.02em] tabular-nums text-ink">{co2}<span className="text-base">t</span></p><p className="mt-1.5 font-mono text-[10px] text-text-3">assumption · {site.re_pour_co2}t per re-pour avoided</p></div></div><div className="mt-3 flex flex-wrap items-center gap-2"><button onClick={onExportCsv} className="flex min-h-11 items-center gap-2 rounded-full border border-line-2 px-4 py-2 text-sm font-medium text-ink transition-colors hover:border-ink/40 focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-surface"><DownloadIcon />export csv</button><button onClick={onExportIcs} className="flex min-h-11 items-center gap-2 rounded-full border border-line-2 px-4 py-2 text-sm font-medium text-ink transition-colors hover:border-ink/40 focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-surface"><DownloadIcon />export ics</button><p className="ml-auto font-mono text-[10px] uppercase tracking-[0.12em] text-text-3">assumption values from site</p></div></section></FadeBlur>
  </aside>
}
